### PR TITLE
Added Japanese, French and Russian Translation

### PR DESCRIPTION
**Pull request by Zeplish**
Japanese translation added.
trade.json : 5% left.
Will finish soon once bounty is confirmed.

### CODE REVIEW

**Comment by Zeplish** [comment]
Translated all the files.

**Comment by daniel-deri** [comment]
Noted, our community member is reviewing your work...

**Comment by Zeplish** [comment]
French and Japanese Added

**Comment by Zeplish** [comment]
> Noted, our community member is reviewing your work...

Perfect!

**Comment by Zeplish** [comment]
Russian Translation Added

**Comment by lolboysg** [comment]
There is a lot of wrong things for the french translation. As a native speaker it doesn't mean anything overall

**Comment by daniel-deri** [comment]
@Zeplish  hi, some update in trade.json and pool.json https://github.com/deri-finance/bounty-program/commit/4ecc7c04275564d15d2a9da5f6b288a23876a331

please update your files, and create pull request again

**Comment by Zeplish** [comment]
OkZeplishSimple Web Design ---- On Fri, 18 Feb 2022 07:34:57 +0530  ***@***.***  wrote ----
@Zeplish  hi, some update in trade.json and pool.json 4ecc7c0
please update your files, and create pull request again

**Comment by daniel-deri** [comment]
ser, our community member has reviewed your japanese translation, we found several inconsistency and false translation. for example 
 "margin usage" translation, margin doesn't mean the "edge or border " here.

  "payoff-tip" : "ペイオフは本源的価値を示します。 <br>コールオプションの最大（ストライク-原資産スポット価格、0）<br>プットオプションの最大（ストライク-原資産スポット価格、0）;",
‘MAX’ should not be translated.

"liq-Price" : "Liq。 価格（推定）", liq. means liquidation.

The list can go on... pls modify your transalation to correct all possible mistakes. 
I also want to stress that using tools such as google translate will result in being disqualified from the Translation Bounty Program.

**Comment by Zeplish** [comment]
> @Zeplish hi, some update in trade.json and pool.json [4ecc7c0](https://github.com/deri-finance/bounty-program/commit/4ecc7c04275564d15d2a9da5f6b288a23876a331)
> 
> please update your files, and create pull request again

Ok.

**Comment by daniel-deri** [comment]
hi, french translation is ready to merge, pls create a separate pull request on french only. Thanks!

**Comment by Zeplish** [comment]
> hi, french translation is ready to merge, pls create a separate pull request on french only. Thanks!

OK. Thanks.

**Pull request closed without merging**
