### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Zeplish**

### CODE REVIEW

**Comment by daniel-deri** [comment]
hi, zeplish, pls do not remove any other folders, simply add fr folder.

**Comment by Zeplish** [comment]
> hi, zeplish, pls do not remove any other folders, simply add fr folder.

Done. I hope this is fine.

**Comment by daniel-deri** [comment]
hi, you didn't apply the bounty. https://gitcoin.co/issue/deri-finance/bounty-program/11/100027694

apply it and I will approve it, then payout the bounty.

**Comment by Zeplish** [comment]
> https://gitcoin.co/issue/deri-finance/bounty-program/11/100027694

hi, I tried applying when you posted it but it does not allow me, showing a message that "someone is already working".

**Comment by daniel-deri** [comment]
try it now

**Comment by Zeplish** [comment]
> try it now

Done.

**Comment by Zeplish** [comment]
> try it now

Hi, could you payout the bounty? Thanks

**Comment by Zeplish** [comment]
> hi, you didn't apply the bounty. https://gitcoin.co/issue/deri-finance/bounty-program/11/100027694
> 
> apply it and I will approve it, then payout the bounty.

@daniel-deri please share the updates.

**Pull request merged**
